#if !canImport(ObjectiveC)
import XCTest

extension MakeSomeCollectionLibTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MakeSomeCollectionLibTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MakeSomeCollectionLibTests.__allTests__MakeSomeCollectionLibTests),
    ]
}
#endif
